**Task1: Using the famous Iris dataset to build a model that can classify iris flowers based on their sepal and petal dimensions.**

**IMPORTING LIBRARIES**

In [ ]:
#importing essential libraries
#as is used for allysing for shorcut
import numpy as np  #for arrays
import matplotlib.pyplot as plt #for graphs
import seaborn as sns #data visualization tool
import pandas as pd #data manipulation
%matplotlib inline

**LOADING THE DATASET**

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
cf = pd.read_csv('/content/sample_data/iris_data.csv')
cf.head(150)

Sepal length  Sepal Width  Petal  length  Petal width     Class_label
0             5.1          3.5            1.4          0.2     Iris-setosa
1             4.9          3.0            1.4          0.2     Iris-setosa
2             4.7          3.2            1.3          0.2     Iris-setosa
3             4.6          3.1            1.5          0.2     Iris-setosa
4             5.0          3.6            1.4          0.2     Iris-setosa
..            ...          ...            ...          ...             ...
145           6.7          3.0            5.2          2.3  Iris-virginica
146           6.3          2.5            5.0          1.9  Iris-virginica
147           6.5          3.0            5.2          2.0  Iris-virginica
148           6.2          3.4            5.4          2.3  Iris-virginica
149           5.9          3.0            5.1          1.8  Iris-virginica

[150 rows x 5 columns]

**VISUALIZATION OF DATASET**

In [ ]:
#Visualize the whole dataset
sns.pairplot(cf,hue="Class_label") #different color combin ations for different class labels

**SEPARATING INPUT AND OUTPUT COLUMNS**

In [ ]:
data = cf.values #data in matrix form
#Creating two new matrix after slicing them
X = data[:,0:4]
Y = data[:,4]
print(X)#-->all rows except Class_Labels Row
print(Y)#-->onlyClass_Labels Row

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.0 1.4 0.1]
 [4.3 3.0 1.1 0.1]
 [5.8 4.0 1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.0 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.0 3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.0 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.0 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.0 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.0 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

**SEPARATING DATA INTO TRAINING AND TESTING**

In [ ]:
#Split the dataset into train and test datasets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2) #120 Rows and 30 Rows = 0.2
#print(Y_train)
#print(X_train)
#print(Y_test)
#print(X_test)

**MODEL 1: Support vector machine algorithm**

In [ ]:
#Support vector machine  algorithm
from sklearn.svm import SVC

model_svc = SVC() #model fitting by training the system
model_svc.fit(X_train , y_train)

SVC()

In [ ]:
predict1 = model_svc.predict(X_test)
#Calculate accuracy of each flower
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test , predict1)*100) #comparing predictions with testing output
#for i in range(len(predict1)):
 # print(y_test[i],predict1[i])--->To check the accuracy obtained




100.0


**MODEL2: LOGISTIC REGRESSION**

In [ ]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
model_LR=LogisticRegression()
model_LR.fit(X_train,y_train)


In [ ]:
predict2 = model_LR.predict(X_test)
#Calculate accuracy of each flower
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test , predict2)*100)

100.0


**MODEL3:DECISION TREE CLASSIFIER**


In [ ]:
#DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier
model_DTC=DecisionTreeClassifier()
model_DTC.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
predict3 = model_svc.predict(X_test)
#Calculate accuracy of each flower
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test , predict3)*100)

100.0


In [ ]:
# A detailed classification report
from sklearn.metrics import classification_report
print(classification_report(y_test , predict2))
#Gives true positives or true negatives or false positives or false negetives


                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00        12
 Iris-virginica       1.00      1.00      1.00         8

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [ ]:
#Manual data by User for Prediction of species
A_new=np.array([[3,2,1,0.2], [4.9,2.2,3.8,1.1], [5.3,2.5,4.6,1.9]])
predict4=model_svc.predict(A_new)
print("Prediction of species: {}" .format(predict4))


Prediction of species: ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
